
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - python3 -m pip install build
    - python3 -m build
    - ls dist/
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - python3 -m pip install dist/*.whl
    - python3 -m pip install pytest
    # python3 -m pytest tests/

deploy:
  stage: deploy
  environment: production
  script:
    - python3 -m pip install twine
    # TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python3 -m twine upload --repository-url https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi --verbose dist/*